apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app.kubernetes.io/name: payment
    app.kubernetes.io/part-of: summit-demo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: payment
  ports:
    - name: http
      port: 8082
      targetPort: http
      protocol: TCP
