apiVersion: application-networking.k8s.aws/v1alpha1
kind: TargetGroupPolicy
metadata:
  name: payment
  namespace: payment
spec:
  targetRef:
    group: ""
    kind: Service
    name: payment
  healthCheck:
    enabled: true
    protocol: HTTP
    path: /health
    intervalSeconds: 10
    timeoutSeconds: 5
    healthyThresholdCount: 2
    unhealthyThresholdCount: 2
    statusMatch: "200"
